version: "3.6"

services:
  pgdb_13:
    container_name: netology_psql
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgbackups:/var/lib/postgresql/backups
    ports:
      - "5432:5432"

volumes:
  pgdata:
    external: true
    name: netology_pgdata
  pgbackups:
    external: true
    name: pgbackups
